plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.noema.tvspeed'
    compileSdk {
        version = release(37) {
            minorApiLevel = 0
        }
    }

    defaultConfig {
        applicationId 'ai.noema.tvspeed'
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName '1.0-final02'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    implementation 'com.wgtunnel:hevtunnel:1.0.4'
}
